version: '3'
services:
  api:
    container_name: api
    build:
      context: .
    environment:
      PGUSER: postgres
      PGPASSWORD: password 
      PGDATABASE: api_dev 
      PGPORT: 5432
      PGHOST: db
    ports:
      - "4000:4000"
    depends_on:
      - db
    tty: true
    volumes: 
      - ./:/home/app
  db:
    container_name: db
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password 
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
